apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::121252337050:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-491GK0NUIEVT
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::121252337050:role/UdacityFlaskDeployCBKubectlRole
      username: build  
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-05T16:56:03Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1659"
  uid: ae741c3a-9529-4b88-a696-d1d40a8c4ce2
